namespace: tigattack
name: onepassword_connect
version: 1.0.1
readme: README.md
authors:
  - tigattack (@tigattack)
description: Retrieve secrets from a 1Password Connect Server via a lookup plugin.
license:
  - MIT
tags:
  - onepassword
  - secrets
  - lookup
  - security
  - connect
repository: https://github.com/tigattack/ansible-onepassword-lookup
documentation: https://github.com/tigattack/ansible-onepassword-lookup
homepage: https://github.com/tigattack/ansible-onepassword-lookup
issues: https://github.com/tigattack/ansible-onepassword-lookup/issues
build_ignore:
  - .venv
  - .github
  - .gitignore
  - requirements.txt
  - '*.tar.gz'
